from typing import Protocol, Optional

from app.domain.business.models.business_model import Business


class BusinessRepositoryPort(Protocol):
    def create(self, business: Business) -> Business: ...
    def find_by_name(self, business_name: str) -> Business: ...
    def find_by_owner_id(self, business_owner_id: int) -> Business: ...

    def find_by_user(self, user_id: int, is_active: Optional[bool] = None) -> Business: ...

    def find_by_id(self, business_id: int) -> Business: ...
    
    def find_by_id_and_user(self, business_id: int, user_id: int) -> Business: ...

    def update(self, business_id: int, business: Business) -> Business: ...

    def delete(self, business_id: int) -> Business: ...
