from datetime import datetime
from typing import Protocol, Optional

from app.domain.business.models.business_member_model import BusinessMember
from app.domain.business.models.member_commission import MemberCommission


class BusinessMemberRepositoryPort(Protocol):
    def create(self, business_member: BusinessMember) -> BusinessMember: ...
    def get_member(self, business_id: int, user_id: int) -> BusinessMember: ...
    def get_member_by_id(self, member_id: int) -> BusinessMember: ...

    def get_by_business_id(self, business_id: int) -> BusinessMember: ...

    def is_owner_or_admin(self, business_id: int, user_id: int) -> bool: ...

    def update(self, business_member: BusinessMember) -> BusinessMember: ...

    def delete(self, member_id: int) -> BusinessMember: ...


    def set_commission(self, commission: MemberCommission) -> MemberCommission: ...

    def get_commission_by_id(self, commission_id: int) -> MemberCommission: ...

    def get_commission(self, member_id: int) -> MemberCommission: ...

    def get_commission_at_date(self, member_id: int, package_id: int, at_date: datetime) -> Optional[MemberCommission]: ...

    def get_current_commission(self, member_id: int, package_id: int) -> Optional[MemberCommission]: ...

    def get_current_business_commission(self, business_id: int) -> Optional[MemberCommission]: ...

    def get_commission_history(self, member_id: int, package_id: int) -> Optional[MemberCommission]: ...

    def update_commission(self, commission: MemberCommission) -> MemberCommission: ...

    def delete_commission(self, commission_id: int) -> bool: ...