from typing import Protocol

from app.domain.user.models.user import User


class UserRepositoryPort(Protocol):
    def create(self, user: User) -> User: ...
    def get_by_id(self, user_id: int) -> User: ...
    def get_by_email(self, email: str) -> User: ...
    def get_all(self) -> list[User]: ...
    def delete(self, user_id: int) -> bool: ...