"""add client first and last name to the appointment and appointment location and duration

Revision ID: 14e054658cfc
Revises: 485f2654cf11
Create Date: 2026-09-25 23:34:42.567910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '14e054658cfc'
down_revision: Union[str, Sequence[str], None] = '485f2654cf11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jotform_field_mapping_target_key'), table_name='jotform_field_mapping')
    op.drop_table('jotform_field_mapping')
    op.add_column('appointments', sa.Column('client_first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('appointments', sa.Column('client_last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('appointments', sa.Column('appointment_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('appointments', sa.Column('appointment_duration', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('appointments', sa.Column('appointment_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('appointments', 'client_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('client_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('appointments', 'appointment_note')
    op.drop_column('appointments', 'appointment_duration')
    op.drop_column('appointments', 'appointment_location')
    op.drop_column('appointments', 'client_last_name')
    op.drop_column('appointments', 'client_first_name')
    op.create_table('jotform_field_mapping',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subkey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['jotform_forms.id'], name=op.f('jotform_field_mapping_form_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('jotform_field_mapping_pkey')),
    sa.UniqueConstraint('form_id', 'target_key', 'priority', name=op.f('uq_form_target_priority'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_jotform_field_mapping_target_key'), 'jotform_field_mapping', ['target_key'], unique=False)
    # ### end Alembic commands ###
