"""initial schema

Revision ID: 3132d19f7dcc
Revises: 
Create Date: 2026-09-04 17:11:53.924919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3132d19f7dcc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jotform_forms_webhook_token'), table_name='jotform_forms')
    op.drop_table('jotform_forms')
    op.drop_table('jotform_credentials')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jotform_credentials',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('jotform_credentials_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name='jotform_credentials_business_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='jotform_credentials_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('jotform_forms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('credential_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('form_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('member_assigns', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('field_mapping', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('webhook_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['package_category.id'], name=op.f('jotform_forms_category_id_fkey')),
    sa.ForeignKeyConstraint(['credential_id'], ['jotform_credentials.id'], name=op.f('jotform_forms_credential_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('jotform_forms_pkey')),
    sa.UniqueConstraint('credential_id', 'form_id', name=op.f('uq_jotform_form'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_jotform_forms_webhook_token'), 'jotform_forms', ['webhook_token'], unique=True)
    # ### end Alembic commands ###
