"""add_packages_commission_jotform_forms

Revision ID: 32916c980d6d
Revises: ba784495fcf9
Create Date: 2026-06-03 23:56:00.687771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '32916c980d6d'
down_revision: Union[str, Sequence[str], None] = 'ba784495fcf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_member_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_member_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('webhook_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jotform_field_map', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_member_id'], ['business_members.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['package_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['package_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('deposit_amount', sa.Integer(), nullable=False),
    sa.Column('remaining_amount', sa.Integer(), nullable=False),
    sa.Column('is_personal', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('appointments', sa.Column('package_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('package_price_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('form_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('price_at_booking', sa.Float(), nullable=False))
    op.add_column('appointments', sa.Column('deposit_amount', sa.Float(), nullable=False))
    op.add_column('appointments', sa.Column('remaining_amount', sa.Float(), nullable=False))
    op.add_column('appointments', sa.Column('commission_percent_at_booking', sa.Float(), nullable=False))
    op.add_column('appointments', sa.Column('commision_amount_at_booking', sa.Float(), nullable=False))
    op.add_column('appointments', sa.Column('is_personal', sa.Boolean(), nullable=False))
    op.alter_column('appointments', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'appointments', 'business_member_form', ['form_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'package_price', ['package_price_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'package', ['package_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.alter_column('appointments', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('appointments', 'is_personal')
    op.drop_column('appointments', 'commision_amount_at_booking')
    op.drop_column('appointments', 'commission_percent_at_booking')
    op.drop_column('appointments', 'remaining_amount')
    op.drop_column('appointments', 'deposit_amount')
    op.drop_column('appointments', 'price_at_booking')
    op.drop_column('appointments', 'form_id')
    op.drop_column('appointments', 'package_price_id')
    op.drop_column('appointments', 'package_id')
    op.drop_table('package_price')
    op.drop_table('package')
    op.drop_table('business_member_form')
    op.drop_table('package_category')
    # ### end Alembic commands ###
