"""change the relationship to user id in appointment to business member id

Revision ID: 38d8318efb9c
Revises: 6282e7b09106
Create Date: 2026-09-22 18:30:22.313620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d8318efb9c'
down_revision: Union[str, Sequence[str], None] = '6282e7b09106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jotform_field_mapping_target_key'), table_name='jotform_field_mapping')
    op.drop_table('jotform_field_mapping')
    op.alter_column('appointments', 'client_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('appointments', 'client_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('appointments', 'commission_percent_at_booking',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('appointments', 'commision_amount_at_booking',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('appointments', 'is_personal',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('appointments_user_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'business_members', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_user_id_fkey'), 'appointments', 'user', ['user_id'], ['id'])
    op.alter_column('appointments', 'is_personal',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('appointments', 'commision_amount_at_booking',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('appointments', 'commission_percent_at_booking',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('appointments', 'client_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('appointments', 'client_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('jotform_field_mapping',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subkey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['jotform_forms.id'], name=op.f('jotform_field_mapping_form_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('jotform_field_mapping_pkey')),
    sa.UniqueConstraint('form_id', 'target_key', 'priority', name=op.f('uq_form_target_priority'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_jotform_field_mapping_target_key'), 'jotform_field_mapping', ['target_key'], unique=False)
    # ### end Alembic commands ###
