"""Add relationship for cascade deletion on field mapping

Revision ID: 6282e7b09106
Revises: bb7e772853d9
Create Date: 2026-09-22 17:45:29.944741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6282e7b09106'
down_revision: Union[str, Sequence[str], None] = 'bb7e772853d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jotform_field_mapping_form_id'), table_name='jotform_field_mapping')
    op.drop_index(op.f('ix_jotform_field_mapping_target_key'), table_name='jotform_field_mapping')
    op.drop_table('jotform_field_mapping')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jotform_field_mapping',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subkey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['jotform_forms.id'], name=op.f('jotform_field_mapping_form_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('jotform_field_mapping_pkey')),
    sa.UniqueConstraint('form_id', 'target_key', 'priority', name=op.f('uq_form_target_priority'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_jotform_field_mapping_target_key'), 'jotform_field_mapping', ['target_key'], unique=False)
    op.create_index(op.f('ix_jotform_field_mapping_form_id'), 'jotform_field_mapping', ['form_id'], unique=False)
    # ### end Alembic commands ###
