"""update the appointment table

Revision ID: 752bbd7ab31c
Revises: 867edea558ca
Create Date: 2026-04-13 20:31:33.756123

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752bbd7ab31c'
down_revision: Union[str, Sequence[str], None] = '867edea558ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('appointments', sa.Column('client_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('appointments', sa.Column('client_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('appointments', sa.Column('appointment_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'appointment_date')
    op.drop_column('appointments', 'client_phone')
    op.drop_column('appointments', 'client_email')
    op.drop_column('appointments', 'client_name')
    # ### end Alembic commands ###
