"""add jotform

Revision ID: 7a833dd559c5
Revises: 3132d19f7dcc
Create Date: 2026-09-04 17:13:42.840765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7a833dd559c5'
down_revision: Union[str, Sequence[str], None] = '3132d19f7dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jotform_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jotform_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member_assigns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('webhook_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['package_category.id'], ),
    sa.ForeignKeyConstraint(['credential_id'], ['jotform_credentials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id', 'form_id', name='uq_jotform_form')
    )
    op.create_index(op.f('ix_jotform_forms_webhook_token'), 'jotform_forms', ['webhook_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jotform_forms_webhook_token'), table_name='jotform_forms')
    op.drop_table('jotform_forms')
    op.drop_table('jotform_credentials')
    # ### end Alembic commands ###
