"""Add jotform assignment table to help manage the assignment of each member category

Revision ID: 7c0a8a809395
Revises: 8bbc52dfc91f
Create Date: 2026-09-13 18:42:45.267120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0a8a809395'
down_revision: Union[str, Sequence[str], None] = '8bbc52dfc91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jotform_form_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('business_member_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_member_id'], ['business_members.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['package_category.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['jotform_forms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_member_id', 'category_id', name='uq_jotform_form_assignment')
    )
    op.drop_table('UniqueConstraint()')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UniqueConstraint()',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('business_member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_member_id'], ['business_members.id'], name=op.f('UniqueConstraint()_business_member_id_fkey')),
    sa.ForeignKeyConstraint(['category_id'], ['package_category.id'], name=op.f('UniqueConstraint()_category_id_fkey')),
    sa.ForeignKeyConstraint(['form_id'], ['jotform_forms.id'], name=op.f('UniqueConstraint()_form_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('UniqueConstraint()_pkey'))
    )
    op.drop_table('jotform_form_assignments')
    # ### end Alembic commands ###
