"""updagrad package table to add package jotform alias to the package

Revision ID: 9c67c72b8aba
Revises: 32916c980d6d
Create Date: 2026-06-17 13:42:13.421463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9c67c72b8aba'
down_revision: Union[str, Sequence[str], None] = '32916c980d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_commission')
    op.add_column('package', sa.Column('jotform_alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'jotform_alias')
    op.create_table('member_commission',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('package_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('commission_percent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('effective_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_member_id'], ['business_members.id'], name=op.f('member_commission_business_member_id_fkey')),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], name=op.f('member_commission_package_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('member_commission_pkey'))
    )
    # ### end Alembic commands ###
