"""change member commission to use amount and flag isPercent

Revision ID: a0f9b9ff233f
Revises: faea708c7cb1
Create Date: 2026-07-08 14:30:21.598735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f9b9ff233f'
down_revision: Union[str, Sequence[str], None] = 'faea708c7cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_commission', sa.Column('commission_amount', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('member_commission', sa.Column('commission_isPercentage', sa.Boolean(), nullable=False, server_default='False'))
    op.drop_column('member_commission', 'commission_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_commission', sa.Column('commission_percent', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('member_commission', 'commission_isPercentage')
    op.drop_column('member_commission', 'commission_amount')
    # ### end Alembic commands ###
