"""add business and business_memeber tables

Revision ID: ba784495fcf9
Revises: 6d27612b1fb6
Create Date: 2026-04-18 14:29:31.077690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ba784495fcf9'
down_revision: Union[str, Sequence[str], None] = '6d27612b1fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webhook_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_members_webhook_token'), 'business_members', ['webhook_token'], unique=True)
    op.alter_column('appointments', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_businesses_webhook_token'), table_name='businesses')
    op.drop_column('businesses', 'webhook_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('webhook_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_businesses_webhook_token'), 'businesses', ['webhook_token'], unique=True)
    op.alter_column('appointments', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_business_members_webhook_token'), table_name='business_members')
    op.drop_table('business_members')
    # ### end Alembic commands ###
