"""Add relationship for cascade deletion

Revision ID: bb7e772853d9
Revises: 0be78db92ba2
Create Date: 2026-09-22 17:26:44.062557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7e772853d9'
down_revision: Union[str, Sequence[str], None] = '0be78db92ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jotform_field_mapping_form_id'), table_name='jotform_field_mapping')
    op.drop_index(op.f('ix_jotform_field_mapping_target_key'), table_name='jotform_field_mapping')
    op.drop_table('jotform_field_mapping')
    op.alter_column('jotform_form_assignments', 'form_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('jotform_form_assignments_form_id_fkey'), 'jotform_form_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'jotform_form_assignments', 'jotform_forms', ['form_id'], ['id'], ondelete='CASCADE')
    op.alter_column('jotform_forms', 'credential_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('jotform_forms_credential_id_fkey'), 'jotform_forms', type_='foreignkey')
    op.create_foreign_key(None, 'jotform_forms', 'jotform_credentials', ['credential_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jotform_forms', type_='foreignkey')
    op.create_foreign_key(op.f('jotform_forms_credential_id_fkey'), 'jotform_forms', 'jotform_credentials', ['credential_id'], ['id'])
    op.alter_column('jotform_forms', 'credential_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'jotform_form_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('jotform_form_assignments_form_id_fkey'), 'jotform_form_assignments', 'jotform_forms', ['form_id'], ['id'])
    op.alter_column('jotform_form_assignments', 'form_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('jotform_field_mapping',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subkey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['jotform_forms.id'], name=op.f('jotform_field_mapping_form_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('jotform_field_mapping_pkey')),
    sa.UniqueConstraint('form_id', 'target_key', 'priority', name=op.f('uq_form_target_priority'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_jotform_field_mapping_target_key'), 'jotform_field_mapping', ['target_key'], unique=False)
    op.create_index(op.f('ix_jotform_field_mapping_form_id'), 'jotform_field_mapping', ['form_id'], unique=False)
    # ### end Alembic commands ###
