"""Add photographer_id to appointments

Revision ID: c6b4c6b12792
Revises: 752bbd7ab31c
Create Date: 2026-04-13 20:38:57.189638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b4c6b12792'
down_revision: Union[str, Sequence[str], None] = '752bbd7ab31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('created_at', sa.DateTime(), nullable=True))

    op.add_column('appointments', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'updated_at')
    op.drop_column('appointments', 'created_at')
    op.drop_column('appointments', 'user_id')
    # ### end Alembic commands ###
