"""Fix field to match API

Revision ID: e71b0c8b86a8
Revises: 991d97a09e09
Create Date: 2026-09-13 17:02:08.998763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e71b0c8b86a8'
down_revision: Union[str, Sequence[str], None] = '991d97a09e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('form_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'jotform_forms', ['form_id'], ['id'])
    op.add_column('jotform_forms', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('jotform_forms', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jotform_forms', 'url')
    op.drop_column('jotform_forms', 'status')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'form_id')
    # ### end Alembic commands ###
