"""add member commission

Revision ID: eb5db285e3df
Revises: 9c67c72b8aba
Create Date: 2026-06-17 15:04:03.982863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb5db285e3df'
down_revision: Union[str, Sequence[str], None] = '9c67c72b8aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_commission',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('package_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('commission_percent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('effective_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_member_id'], ['business_members.id'], name=op.f('member_commission_business_member_id_fkey')),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], name=op.f('member_commission_package_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('member_commission_pkey'))
    )
    # ### end Alembic commands ###
