"""Remove the category and business member in the jotform form db

Revision ID: f2fa0205112b
Revises: 7c0a8a809395
Create Date: 2026-09-13 18:47:05.486803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2fa0205112b'
down_revision: Union[str, Sequence[str], None] = '7c0a8a809395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('jotform_forms_category_id_fkey'), 'jotform_forms', type_='foreignkey')
    op.drop_column('jotform_forms', 'member_assigns')
    op.drop_column('jotform_forms', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jotform_forms', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('jotform_forms', sa.Column('member_assigns', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('jotform_forms_category_id_fkey'), 'jotform_forms', 'package_category', ['category_id'], ['id'])
    # ### end Alembic commands ###
