from datetime import datetime
from typing import List, Protocol, Optional

from app.domain.appointment.models.appointment_model import Appointment


class AppointmentRepositoryPort(Protocol):
    def create(self, appointment: Appointment) -> Appointment: ...
    def find_by_business(self, business_id: int, status: Optional[str] = None) -> Optional[Appointment]: ...
    def get_appointment_by_photographer(self, member_id: int, business_id: Optional[int] = None, status: Optional[str] = None) -> Optional[Appointment]: ...
    def get_appointment_by_id(self, appointment_id: int, member_id:Optional[int] = None, status : Optional[str] = None) -> Optional[Appointment]:...
    def find_booked_or_dated_between(self, business_id: int, start: datetime, end: datetime) -> List[Appointment]:
        """Appointments of the business whose booking date or appointment date falls in [start, end]."""
    def update(self, appointment: Appointment, appointment_id: int) -> Appointment: ...

    def update_status(self, appointment: Appointment) -> Appointment: ...
    def update_totals(self, appointment: Appointment) -> Appointment:
        """Persist price, remaining amount, commission, duration and member exactly as set, None included."""
    def delete(self, appointment_id: int) -> bool: ...