from typing import Protocol, Optional

from app.domain.appointment.models.appointment_model import Appointment


class AppointmentRepositoryPort(Protocol):
    def create(self, appointment: Appointment) -> Appointment: ...
    def find_by_business(self, business_id: int, status: Optional[str] = None) -> Optional[Appointment]: ...
    def get_appointment_by_photographer(self, user_id: int, business_id: Optional[int] = None, status: Optional[str] = None) -> Optional[Appointment]: ...
    def get_appointment_by_id(self, appointment_id: int,user_id:Optional[int] = None, status : Optional[str] = None) -> Optional[Appointment]:...
    def update(self, appointment: Appointment, appointment_id: int) -> Appointment: ...
    def delete(self, appointment_id: int) -> bool: ...