from datetime import datetime
from typing import Protocol, List

from app.domain.package.models.package_price import PackagePrice


class PackagePriceRepositoryPort(Protocol):
    def create(self, package_price: PackagePrice) -> PackagePrice:...
    def update(self, package_price: PackagePrice, package_price_id: int) -> PackagePrice:...
    def delte(self, package_price_id: int) -> bool: ...
    def get_price_at_date(self, package_id: int, date: datetime) -> PackagePrice: ...
    def get_package_price(self, package_price_id: int) -> PackagePrice: ...
    def get_current_price(self, package_id: int) -> PackagePrice: ...
    def get_price_history(self, package_id: int) -> List[PackagePrice]: ...