from typing import Protocol, Optional, List

from app.domain.package.models.package import Package
from app.domain.package.models.package_category_model import PackageCategory


class PackageRepositoryPort(Protocol):
    def create_package(self, package: Package) -> Package: ...
    def update_package(self, package: Package) -> Package: ...
    def delete_package(self, package_id: int) -> bool: ...
    def get_package_by_id(self, package_id: int) -> Optional[Package]: ...
    def get_packages_by_business_id(self, business_id: int, is_active: bool = True) -> Optional[List[Package]] : ...
    def get_by_category(self, category_id:int, is_active: bool = True) -> List[Package]: ...
    def create_package_category(self, package_category: PackageCategory) -> PackageCategory: ...
    def delete_package_category(self, package_category_id: int) -> bool:...
    def update_package_category(self, package_category: PackageCategory) -> PackageCategory: ...
    def get_categories_by_business(self, business_id: int) -> List[PackageCategory]: ...
    def find_package_by_alias(self, business_id: int, category_id: int, alias_raw_value: str) -> Package: ...
    def get_category_by_id(self, category_id: int) -> Optional[PackageCategory]: ...

