from typing import Protocol

from app.domain.Jotform.models.jotform_form_model import JotformForm, JotformCredential


class JotformRepositoryPort(Protocol):
    def create_credential(self, credential: JotformCredential) -> JotformCredential: ...

    def get_credential_by_id(self, credential_id: int) -> JotformCredential: ...

    def get_credential_by_business(self, business_id: int) -> JotformCredential: ...

    def update_credential(self, credential: JotformCredential) -> JotformCredential: ...

    def delete_credential(self, credential_id: int) -> bool: ...

    def create_form(self, form:JotformForm) -> JotformForm: ...

    def get_form_by_id(self, jotform_id: int) -> JotformForm: ...

    def get_form_by_webhook_token(self, webhook_token: str) -> JotformForm: ...

    def get_form_by_business_id(self, business_id: int) -> JotformForm: ...

    def get_form_by_category_id(self, category_id: int) -> JotformForm: ...

    def get_form_by_category_and_member(self, category_id: int, member_id: int) -> JotformForm: ...

    def update_form(self, form: JotformForm) -> JotformForm: ...

    def delete_form(self, form: JotformForm) -> bool: ...
