from typing import Protocol, List, Optional

from app.domain.Jotform.models.jotform_field_mapping import JotformFieldMapping
from app.domain.Jotform.models.jotform_form_model import JotformForm, JotformCredential, JotformFormAssignment


class JotformRepositoryPort(Protocol):
    def create_credential(self, credential: JotformCredential) -> JotformCredential: ...

    def get_credential_by_id(self, credential_id: int) -> JotformCredential: ...

    def get_credential_by_business(self, business_id: int) -> JotformCredential: ...

    def update_credential(self, credential: JotformCredential) -> JotformCredential: ...

    def delete_credential(self, credential_id: int) -> bool: ...

    def create_form(self, form:JotformForm) -> JotformForm: ...

    def get_form_by_id(self, jotform_id: int) -> JotformForm: ...

    def get_form_by_webhook_token(self, webhook_token: str) -> JotformForm: ...

    def get_forms_by_business_id(self, business_id: int) -> List[JotformForm]: ...

    def get_form_by_credential_id(self, credential_id: int) -> List[JotformForm]: ...

    def update_form(self, form: JotformForm) -> JotformForm: ...

    def delete_form(self, form: JotformForm) -> bool: ...

    def create_assignment(self, assignment: JotformFormAssignment) -> JotformFormAssignment: ...

    def get_assignment_by_member_and_category(self, business_member_id: int, category_id: int) -> Optional[
        JotformFormAssignment]: ...

    def get_assignments_for_form(self, form_id: int) -> List[JotformFormAssignment]: ...

    def delete_assignment(self, assignment_id: int) -> bool: ...

    def get_form_by_category_and_member(self, category_id: int, member_id: int) -> Optional[JotformForm]: ...

    def set_field_mappings(self, form_id: int, mappings: list[JotformFieldMapping]) -> list[JotformFieldMapping]: ...

    def get_field_mappings(self, form_id: int) -> list[JotformFieldMapping]: ...

    def get_mapping_by_qid(self, form_id: int, qid: str) -> Optional[JotformFieldMapping]: ...

    def get_assignment_by_form_and_category(self, form_id: int, category_id: int) -> Optional[JotformFormAssignment]:
        """Returns the assignment only when exactly one member is assigned to this form+category.
        Returns None when zero OR multiple assignments exist — both cases require manual resolution."""
