from typing import Protocol, Optional, List

from app.domain.addon.models.addon import Addon


class AddonRepositoryPort(Protocol):
    def create(self, addon: Addon) -> Addon: ...
    def update(self, addon: Addon) -> Addon: ...
    def get_by_id(self, addon_id: int) -> Optional[Addon]: ...
    def list_by_business(self, business_id: int, is_active: Optional[bool] = None) -> List[Addon]: ...
    def find_by_alias(self, business_id: int, alias: str) -> List[Addon]:
        """Every add-on of the business, active or not, whose normalized alias equals `alias`."""
