from typing import Protocol, Optional, List, Dict, Iterable, Set

from app.domain.addon.models.appointment_addon import AppointmentAddon
from app.domain.addon.models.unresolved_addon import UnresolvedAddon
from app.domain.appointment.models.appointment_model import Appointment


class AppointmentAddonRepositoryPort(Protocol):
    def add(self, line: AppointmentAddon) -> AppointmentAddon: ...
    def update(self, line: AppointmentAddon) -> AppointmentAddon: ...
    def remove(self, appointment_addon_id: int) -> bool: ...
    def apply_changes(self, appointment: Appointment, removed_ids: List[int], updated: List[AppointmentAddon],
                      added: List[AppointmentAddon]) -> None:
        """Write the removals, updates and additions of the lines together with the appointment totals, all or nothing."""

    def get(self, appointment_id: int, addon_id: int) -> Optional[AppointmentAddon]: ...
    def list_for_appointment(self, appointment_id: int) -> List[AppointmentAddon]: ...
    def list_for_appointments(self, appointment_ids: Iterable[int]) -> Dict[int, List[AppointmentAddon]]: ...
    def exists_for_addon(self, addon_id: int) -> bool:
        """True once any Appointment Add-on references the add-on."""

    def add_unresolved_addon(self, unresolved: UnresolvedAddon) -> UnresolvedAddon: ...
    def get_unresolved_addon(self, unresolved_id: int) -> Optional[UnresolvedAddon]: ...
    def update_unresolved_addon(self, unresolved: UnresolvedAddon) -> UnresolvedAddon: ...
    def list_unresolved_addons_for_appointments(
        self, appointment_ids: Iterable[int]
    ) -> Dict[int, List[UnresolvedAddon]]:
        """Only the Unresolved Add-ons still waiting for resolution."""
    def appointment_ids_with_unresolved_addons(self, business_id: int) -> Set[int]: ...
