from typing import Protocol, Optional, List, Dict, Iterable

from app.domain.addon.models.appointment_addon import AppointmentAddon


class AppointmentAddonRepositoryPort(Protocol):
    def add(self, line: AppointmentAddon) -> AppointmentAddon: ...
    def update(self, line: AppointmentAddon) -> AppointmentAddon: ...
    def remove(self, line_id: int) -> bool: ...
    def get(self, appointment_id: int, addon_id: int) -> Optional[AppointmentAddon]: ...
    def list_for_appointment(self, appointment_id: int) -> List[AppointmentAddon]: ...
    def list_for_appointments(self, appointment_ids: Iterable[int]) -> Dict[int, List[AppointmentAddon]]: ...
    def exists_for_addon(self, addon_id: int) -> bool:
        """True once any Appointment Add-on references the add-on."""
